config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :reviews
  resources :books do
    collection do
      post 'create_index'
    end
  end
  resources :authors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'
  get 'top_sellings', to: "books#top_selling"
  get 'top_rated', to: "books#top_rated"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
  end
  

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Home</title>
</head>
<body>
  <h1>Welcome to the Book Review Application</h1>
  <p>Navigate to the CRUD sections below:</p>

  <ul>
    <li><a href="<%= authors_path %>">Authors</a></li>
    <li><a href="<%= books_path %>">Books</a></li>
    <li><a href="<%= reviews_path %>">Reviews</a></li>
    <li><a href="<%= sales_path %>">Sales</a></li>
  </ul>
  <p>Or check out the many different statistics we offer:</p>
  <ul>
    <li><a href="/top_sellings">Top Selling Books</a></li>
    <li><a href="<%= "/top_rated" %>">Top Rated Books</a></li>

    <div>
       <%= image_tag "home_image.jpg", alt: "Home Image", class: "home-page-image" %>
  </div>
</ul>
</body>
</html>