config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :reviews
  resources :books do
    collection do
      post 'create_index'
    end
  end
  resources :authors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'
  get 'top_sellings', to: "books#top_selling"
  get 'top_rated', to: "books#top_rated"
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ show edit update destroy ]

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1 or /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
    @possible_books = Book.all
  end

  # GET /reviews/1/edit
  def edit
    @possible_books = Book.all
  end

  # POST /reviews or /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to review_url(@review), notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to review_url(@review), notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy!

    respond_to do |format|
      format.html { redirect_to reviews_url, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:book_id, :review, :score, :number_of_upvotes)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_with(model: review) do |form| %>
  <% if review.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :book_id, style: "display: block" %>
    <%= form.collection_select :book_id, @possible_books, :id, :name, prompt: "Select a book" %>
  </div>

  <div>
    <%= form.label :review, style: "display: block" %>
    <%= form.text_area :review %>
  </div>

  <div>
    <%= form.label :score, style: "display: block" %>
    <%= form.number_field :score %>
  </div>

  <div>
    <%= form.label :number_of_upvotes, style: "display: block" %>
    <%= form.number_field :number_of_upvotes %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<div id="<%= dom_id review %>">
  <p>
    <strong>Book:</strong>
    <%= review.book_id %>
  </p>

  <p>
    <strong>Review:</strong>
    <%= review.review %>
  </p>

  <p>
    <strong>Score:</strong>
    <%= review.score %>
  </p>

  <p>
    <strong>Number of upvotes:</strong>
    <%= review.number_of_upvotes %>
  </p>

</div>

app/views/reviews/_reviews_list.html.erb
<% if reviews.any? %>
  <table class="table">
    <thead>
      <tr>
        <th>Book</th>
        <th>Review</th>
        <th>Score</th>
        <th>Upvotes</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% reviews.each do |review| %>
        <tr>
          <td><%= link_to review.book.name, review.book %></td>
          <td><%= truncate(review.review, length: 50) %></td>
          <td><%= review.score %> / 5</td>
          <td><%= review.number_of_upvotes %></td>
          <td><%= link_to 'Show', review %></td>
          <td><%= link_to 'Edit', edit_review_path(review) %></td>
          <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No reviews found.</p>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Show this review", @review %> |
  <%= link_to "Back to reviews", reviews_path %>
</div>

app/views/reviews/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reviews</h1>

<%= link_to "New review", new_review_path %>

<%= render 'reviews_list', reviews: @reviews %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Back to reviews", reviews_path %>
</div>

app/views/reviews/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @review %>

<div>
  <%= link_to "Edit this review", edit_review_path(@review) %> |
  <%= link_to "Back to reviews", reviews_path %>

  <%= button_to "Destroy this review", @review, method: :delete %>
</div>