config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :reviews
  resources :books do
    collection do
      post 'create_index'
    end
  end
  resources :authors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'
  get 'top_sellings', to: "books#top_selling"
  get 'top_rated', to: "books#top_rated"
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :book
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: %i[ show edit update destroy ]

  # GET /sales or /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1 or /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new

    @possible_books = Book.all
  end

  # GET /sales/1/edit
  def edit
    @possible_books = Book.all
  end

  # POST /sales or /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to sale_url(@sale), notice: "Sale was successfully created." }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1 or /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to sale_url(@sale), notice: "Sale was successfully updated." }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1 or /sales/1.json
  def destroy
    @sale.destroy!

    respond_to do |format|
      format.html { redirect_to sales_url, notice: "Sale was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sale_params
      params.require(:sale).permit(:book_id, :year, :sales)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_with(model: sale) do |form| %>
  <% if sale.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
        <% sale.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :book_id, style: "display: block" %>
    <%= form.collection_select :book_id, @possible_books, :id, :name, prompt: "Select a book" %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.date_field :year %>
  </div>

  <div>
    <%= form.label :sales, style: "display: block" %>
    <%= form.number_field :sales %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sales/_sale.html.erb
<div id="<%= dom_id sale %>">
  <p>
    <strong>Book:</strong>
    <%= sale.book_id %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= sale.year %>
  </p>

  <p>
    <strong>Sales:</strong>
    <%= sale.sales %>
  </p>

</div>

app/views/sales/_sales_list.html.erb
<% if sales.any? %>
  <table class="table">
    <thead>
      <tr>
        <th>Book</th>
        <th>Year</th>
        <th>Sales</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% sales.each do |sale| %>
        <tr>
          <td><%= link_to sale.book.name, sale.book %></td>
          <td><%= sale.year.strftime("%Y") %></td>
          <td><%= number_with_delimiter(sale.sales, delimiter: ',') %></td>
          <td><%= link_to 'Show', sale %></td>
          <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
          <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No sales records found.</p>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing sale</h1>

<%= render "form", sale: @sale %>

<br>

<div>
  <%= link_to "Show this sale", @sale %> |
  <%= link_to "Back to sales", sales_path %>
</div>

app/views/sales/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sales</h1>

<%= link_to "New sale", new_sale_path %>

<%= render 'sales_list', sales: @sales %>

app/views/sales/new.html.erb
<h1>New sale</h1>

<%= render "form", sale: @sale %>

<br>

<div>
  <%= link_to "Back to sales", sales_path %>
</div>

app/views/sales/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sale %>

<div>
  <%= link_to "Edit this sale", edit_sale_path(@sale) %> |
  <%= link_to "Back to sales", sales_path %>

  <%= button_to "Destroy this sale", @sale, method: :delete %>
</div>